---
# Pipeline configuration for Concourse CI (http://concourse.ci)

resources:





# Application Source Code Resource
# --------------------------------
# Tells the pipeline where to get the app's source code.
# Configuration definition found at
#   https://github.com/concourse/git-resource
- name: resource-fancyapp-source-git
  type: git
  source: 
    uri: https://github.com/jaustinhughey/cf-env
    branch: master






# Application Deployment Resource
# -------------------------------
# Tells the pipeline how to deploy the application to
# Cloud Foundry. To tell it where your CF API end point
# is located, run `cf api` within your shell to see where
# your `cf` tool is sending its API queries. Then just
# copy/pasta that value below. Other variables/values
# can be seen here:
#   https://github.com/concourse/cf-resource
#
# TODO: Make ./credentials.yml and put creds *there*, not
#       in this file directly. Because who needs security,
#       amirite?! :trollface:
- name: resource-cf-deploy
  type: cf
  source:
    skip_cert_check: true
    api: https://api.bosh-lite.com
    organization: snw
    space: batcave
    username: admin
    password: admin







jobs:

# Application Deployment (Cloud Foundry)
# --------------------------------------
# Tells the pipeline what it needs to know in order to
# automatically "push" a deployment of your application
# to your Cloud Foundry "resource" (see above).
- name: job-deploy-app
  public: true
  serial: true
  plan:
  - get: resource-fancyapp-source-git
    trigger: true

  - put: resource-cf-deploy
    params:
      manifest: resource-fancyapp-source-git/manifests/fancyapp.yml
      path: resource-fancyapp-source-git
